name: build-application
on: workflow_dispatch
jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: code compilation
        run: mkdir -p bin
          make build