name: print-infos-machine
on: workflow_dispatch
jobs:
  print-infos-machine:
    runs-on: ubuntu-latest
    steps:
      - name: informations sur la machine
        run: hostnamectl
      - name: adressage ipv4
        run: ip -4 a
      - name: mon identit√© de connexion
        run: whoami