name: Sysinfo - Build, Test et Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
    tags:
      - 'v*.*.*'

permissions:
  id-token: write  # Requis pour la signature
  contents: write  # Requis pour les releases et les artifacts
  packages: write  # Requis pour les packages
  attestations: write  # Requis pour l'attestation

jobs:
  # --- Jobs pour les branches de travail ---
  python-lint:
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Installation des dépendances
        run: pip install ifaddr psutil pylint
      - name: Analyse du code Python
        run: pylint --disable=missing-docstring script/mysystem/mysystem.py

  python-test:
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest
    needs: python-lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Installation des dépendances
        run: pip install ifaddr psutil
      - name: Exécution du test
        run: python script/mysystem/mysystem.py

  c-lint:
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Analyse du code C
        run: make lint

  c-build-sysinfo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build artifact
        run: |
          mkdir -p bin
          make build
      - name: Generate attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'bin/sysinfo'
      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sysinfo-binary-${{ github.sha }}
          path: bin/sysinfo

  c-run-sysinfo:
    if: github.ref_type != 'tag'  # Uniquement pour les branches
    runs-on: ubuntu-latest
    needs: c-build-sysinfo
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sysinfo-binary-${{ github.sha }}
      - name: Run sysinfo
        run: |
          chmod +x sysinfo
          ./sysinfo

  # --- Job pour les releases (tags) ---
  c-run-release-sysinfo:
    if: contains(github.ref, 'tag')
    runs-on: ubuntu-latest
    needs: c-build-sysinfo
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sysinfo-binary-${{ github.sha }}
      - name: Release sysinfo
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: sysinfo
