name: sysinfo-release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  c-run-release-sysinfo:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    needs: c-build-sysinfo
    steps:
      - name: sysinfo checkout
        uses: actions/checkout@v6
      - name: sysinfo download artifact
        uses: actions/download-artifact@v4
        with:
          name: sysinfo-binary-${{ github.sha }}
      - name: release sysinfo
        uses: softprops/action-gh-release@v2
        with:
          files: sysinfo-binary-${{ github.sha }}