name: sysinfo-release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  c-run-release-sysinfo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: sysinfo checkout
        uses: actions/checkout@v6
      - name: sysinfo download artifact
        uses: actions/download-artifact@v4
        with:
          name: sysinfo-binary-latest
      - name: release sysinfo
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: sysinfo-binary-latest