name: apps-build
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
    tags-ignore:
      - '**'

permissions:
  id-token: write # requis pour signer
  contents: read
  attestations: write # requis pour créer l'attestation

jobs:
  python-lint:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Installation des dépendances
        run: pip install ifaddr psutil pylint
      - name: Analyse du code python
        run: pylint --disable=missing-docstring script/mysystem/mysystem.py
  python-test:
    if: false
    runs-on: ubuntu-latest
    needs: python-lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Installation des dépendances
        run: pip install ifaddr psutil
      - name: Exécution du test
        run: python script/mysystem/mysystem.py
  c-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Analyse du code c
        run: make lint
  c-build-sysinfo:
    runs-on: ubuntu-latest
    needs: c-lint
    steps:
      - uses: actions/checkout@v4
      - name: build artifact
        run: |
          mkdir -p bin
          make build
      - name: Generate attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'bin/sysinfo'
      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sysinfo-binary-${{ github.sha }}
          path: bin/sysinfo
  c-run-sysinfo:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    needs: c-build-sysinfo
    steps:
      - name: sysinfo checkout
        uses: actions/checkout@v6
      - name: sysinfo download artifact
        uses: actions/download-artifact@v4
        with:
          name: sysinfo-binary-${{ github.sha }}
      - name: run sysinfo
        run: |
          chmod +x sysinfo
          ./sysinfo